### ISSUE TITLE
Tradurre "Needy" in italiano

### ISSUE THREAD

**Issue by jaramir** [bombmanual/italian#4]
Stavo pensando di tradurre "Needy" con "bisognoso". @brugnara cosa ne pensi?

**Comment by brugnara** [comment]
L'ho volutamente lasciato in inglese non sapendo cosa mettere. Bisognoso è effettivamente la traduzione letterale e sta anche abbastanza bene. Non saprei se ci sono termini più adatti però "modulo bisognoso" rende l'idea, soprattutto perché nel capitolo che li introduce, è comunque spiegato cosa significa quindi potrebbe funzionare. Bene, @jaramir

**Comment by brugnara** [comment]
#7
