### ISSUE TITLE
Nuova immagine del codice morse 

### ISSUE THREAD

**Issue by jaramir** [bombmanual/italian#5]
L'immagine del codice morse è diversa dal manuale più recente in inglese.

**Comment by brugnara** [comment]
@jaramir ho controllato ma mi sembrano identiche.

http://bombmanual.github.io/italian/
http://www.bombmanual.com/manual/1/html/index.html

e anche sul PDF mi sembra uguale
http://www.bombmanual.com/manual/1/pdf/Bomb-Defusal-Manual_1.pdf

Dove hai notato questa differenza?

**Comment by jaramir** [comment]
Ho stampato il manuale dal link di Steam: http://cdn.akamai.steamstatic.com/steam/apps/341800/manuals/Bomb-Defusal-Manual_1.pdf?t=1450113343

Che sia una vecchia revisione?

**Comment by jaramir** [comment]
Confermo. Stavo guardando (ed ho pure stampato) la revisione 2. Sorry!
